title: Don't use Replit!
description: Why you should stop uing Replit, and some alternatives
theme: just-the-docs

url: https://dontuserepl.com

aux_links:
  GitHub Repository: https://github.com/dontuserepl/why
